### ISSUE TITLE
Converting current price to Euro.

### ISSUE THREAD

**Issue by PvDam** [frittna/Crypto_Coin_Ticker#1]
Really like your Crypto Ticker. Right now only a handful of margin trading pairs are available through the Binance API, against USD or USDT. None of them to the Euro.
Would it be possible to somehow convert the current price in the lower left of the screen to Euro's?

**Comment by frittna** [comment]
Hi, thank you. 
What pairs are you looking for, for example?
I tried to modify the code in line number 90+91 to from "BTCUSDT" and "btcusdt" to "BTCEUR" and "btceur" which will show the regulair Bitcoin to Euro price at the spot market. 
On binance ther are only 4 markets to Euro at all (BTC, ETH, XRP and BNB).
Or do you mean you want to show a converted value of the usdt to euro like 1$ = 0.92€ for any currency just for the euro feeling?

**Comment by PvDam** [comment]
Hello,

Thanks for the quick response!

I would just be interested in BTCEUR to update every minute. But Binance will ony do minute updates for certain pairs and none of them are Euro. So then I would say a converted value from $ to € would do fine. But then still somehow the conversion rate must be retrieved.

Grtz,
Patrick

**Comment by PvDam** [comment]
I already changed the pair in line 90+91 to BTCEUR and btceur but then the current price isn’t refreshed every 2sec and the candles look strange.

**Comment by frittna** [comment]
that is ok, the market has a very low trading volume at this moment as we write and the price is not moving fast. In 1Month-Timeframe the pair draws only a few candles as it is listed only since a few months from now.

**Comment by PvDam** [comment]
Do you think it’s possible to just convert the Dollar price to the Euro. In that case everything else stays the same.

**Comment by frittna** [comment]
it would be possible but a bit pointless in my view because in a bit longer timeframes like 15m its rather ok.

and if the market is more volatile because more people are buying and selling the update rate is ok too.

Its just like if you hold any shit coin and want to look at it, it is the same, the market is often not moving for hours or at least some minutes, what you see is what is traded on binance.

If you convert the dollar to euro by force you have two problems, like you said before the price rate is changing over the weeks and it would be complicated to add a euro/dollar price update into the code.

The second thing is that it would show a converted price but the price would not be "real" because the moving does not exist on the euro pair market, it would be some kind of fake values.

**Comment by PvDam** [comment]
All good arguments!

So, for now I keep it on BTC/EUR. Maybe Binance will add the BTC/EUR pair for margin trading and get a faster update rate.
