### ISSUE TITLE
Updates needed

### ISSUE THREAD

**Issue by Michail1** [frittna/Crypto_Coin_Ticker#2]
LiteCoin should be Litecoin
Etherium should be Ethereum

Bitcoin color should be Orange.

Typically, a 1minute (for example) candle should not have a high/low for 1 minute candle period.  It should be either an hour or typically a 24 hour period.  Love seeing the candles at 1 minute, but a high/low for 24 hours.  

I've made the above changes to the code, but thought I would mention them to you.  Thanks for bringing the M5Stack to my attention.  I love it.

Love the project.  Great job.

**Comment by frittna** [comment]
Hi, i'm glad that you like it, 

> LiteCoin should be Litecoin
> Etherium should be Ethereum
> Bitcoin color should be Orange.

Thanks, i fixed the spelling. And I had BITCOIN i orange in the beginning but because i have 4 selectable brightness levels and i often i use it on the darkest brightness level which is rather dark on my older M5Stack and the orange i used was not very visible, epecially when running for quite a long time in hotter areas. (my second newer M5-Stack has much better lcd quality and is not warming up that much)

But that's why i have described some example colours in the outcommented section and you can use any color you want for everything.  

The colours and surely more important the selected coins are intended to be changed by every user individually. I guess the requested work to run the program involves that this person at least flies over the explaination about the coins and what can be shown and that any coin (listed in Binance com) or colours can be used.. 

Also the number of selectable coins (8 at the moment) is just an illustration that you can pick your coin selection or as many or few you like (1-255). I selected these 8 coins only because of their wide price ranges and to test their candle visualisation. I mean BTC price range is far over 1000, some are over 1, some are under 0.001 or much smaller, it was a pain for me as rather unprofessional rookie after all to get the calculations right. The candles would look veeery choppy if i would not adjust the price because it has to draw the price in a grid of only 200pixels in height, so a 0.00002 price for example and its movements would be just be lost in rounding. I multiply or divide my millions and or so on to get a higher resulution. I'm sure the solution is kind of brute force and not very stylish code but it is working in all cases i tested even when overlapping a price range (in months-time-frame mostly). 

> Typically, a 1minute (for example) candle should not have a high/low for 1 minute candle period. It should be either an hour or typically a 24 hour period. Love seeing the candles at 1 minute, but a high/low for 24 hours.

The high/low values on the bottom right is always taken from the 24 visible candles in your selected timeframe, so the last 24minutes if on 1min timeframe. (Your wrote min/max of only 1min?? dont know how you mean it) 
It is not perfect after all i know, i wish i could additional show the last 24hr's high/low's even while in a small timeframe like 1,3,5,and15min BUT therefore i would need to load the last 24 1-hour candles from binance and not the last 24 1-min candles (for example) to get the data. 
i think its possible to implement a loading of the last 24 1-h candles on startup to store them and refresh them every 1h to show these data when using small timeframes under 15m.. but i don't know if i will implement soon, maybe

**Comment by Michail1** [comment]
Great.
Again, the project is awesome.   I admit, I had to spend time on another project, but will get back to this one and notify you if I see other issues and/or make suggestions.

Michail
www.voltagegoat.com

**Comment by frittna** [comment]
thank you, you're very welcome, i made no futher progress so far too but time will come i guess

**Comment by frittna** [comment]
btw: GREAT site with much love to btc-tickers, etc,  i totally agree!!!
