### ISSUE TITLE
crypto cycle and alarm clock ?

### ISSUE THREAD

**Issue by reddai75** [frittna/Crypto_Coin_Ticker#5]
Outstanding job! It would become the perfect alarm clock if you could add an alarm... may be with an mp3 of choice in the sd ? (ok I'm going too far now) and... what about automatically cycling every X seconds with the selected crypto ?
anyway, your project is great!

**Comment by frittna** [comment]
thank you, i think cycling through the coins would not be a big deal to code and i think about implementing it soon.
Alarms or other simple features could be added drip by drip BUT the major problem i see is (beside this is a hobby fun project and my coding skills are rather poor) that there is a kind of barrier for innovations in the program since i am unable to implement a more comfable method to import personal user settings and other settings you want to have for short therm.

I mean if we had a better method than from the SD-Card, a nice interface to send simple values to the M5Stack e.g from mobile phone or a pc-script, everything would be much more comfortable and inspiring to implement more and more features. (alarms, triggers to do something, sound, outgoing messages, bot trades via email, etc etc...)

and you have not to fight with a small menu on little M5 with its 3 buttons. The only way would be to get a network app or pc-app (or email clien on the m5?) but thats above my coding skills i think.   

(f.y.i.: there is a product called "Ticrthing" i experienced some time ago, it has this "configuring by app" feature but its not an open project)

**Comment by frittna** [comment]
cycling feature added

**Comment by reddai75** [comment]
It works flawlessy! and at least on my AP, it supports spaces on SSID

**Comment by reddai75** [comment]
Well that's weird, my ssd has spaces and it worked until today.  This morning I updated the cfg file and now it does not connect anymore...
