### ISSUE TITLE
Refresh interval

### ISSUE THREAD

**Issue by sBooz** [frittna/Crypto_Coin_Ticker#8]
Stunning project. Very well done. Thank you very much!
Short question, is it possible to change the refresh interval? If it is placed beside the Computer Monitor, it is a bit sturbing if it refreshes every .5 second.

Thank you in advance, sBooz

**Comment by frittna** [comment]
hi, thx
short answer: sounds odd but no, as i understand the refrehsh intervall in the data stream is fixed to 2 seconds , 2000ms.
Here is the documentation about candle stream from the websocket: https://github.com/binance/binance-spot-api-docs/blob/master/web-socket-streams.md#klinecandlestick-streams
Maybe there would be an solution to add some delay at certain point but then i think the code would need much more changings, for example the buttons will not response while the delay is set, the stream would be open, therefore you would need to connect and close every set intervall.
But well, i'm sure it would be possible, otherwise, to be honest, 2s refresh rate for the price value was never very disturbing to me, maybe if you are on 1 minute timeframe and there is a big price movement outside the range, then all the 24 candles and  not only the last one and the price value are redrawn which causes a slightly flicker (clear screen commant).

**Comment by sBooz** [comment]
Thank you very much for the explanation. You are right, it is not very disturbing, but if you have it below the computer monitor in front of you, it is a bit irritating when it changes every 2 seconds. :-) But anyway it is great and I love it very much.
Best Regards, sBooz
